version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - appnet

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  nest-api:
    build: ./services/nest-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASS=${DEFAULT_ADMIN_PASS}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - appnet

  go-worker:
    build: ./services/go-worker
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - NEST_API_URL=${NEST_API_URL}
      - WORKER_MAX_RETRIES=${WORKER_MAX_RETRIES}
      - WORKER_HTTP_TIMEOUT_SECONDS=${WORKER_HTTP_TIMEOUT_SECONDS}
    depends_on:
      - rabbitmq
      - nest-api
    restart: unless-stopped
    networks:
      - appnet

  weather-producer:
    build: ./services/python-producer
    environment:
      - LAT=${LAT}
      - LON=${LON}
      - CITY=${CITY}
      - INTERVAL_SECONDS=${INTERVAL_SECONDS}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
    depends_on:
      - rabbitmq
    restart: unless-stopped
    networks:
      - appnet

  frontend:
    build:
      context: ./services/frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_DEFAULT_CITY=${CITY}
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - nest-api
    networks:
      - appnet

volumes:
  mongo-data:

networks:
  appnet:
    driver: bridge
